/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v7.0
processor: LPC54114J256
package_id: LPC54114J256BD64
mcu_data: ksdk2_0
processor_version: 7.0.1
board: LPCXpresso54114
functionalGroups:
- name: BOARD_InitPeripherals_cm4
  UUID: 35304192-dcd2-4c25-bdf3-6c9c60ec1aa8
  called_from_default_init: true
  selectedCore: cm4
- name: BOARD_InitPeripherals_cm0plus
  UUID: 52029ed6-c35d-48dd-bb29-3c4ad79cee97
  selectedCore: cm0plus
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'msg'
- type_id: 'msg_6e2baaf3b97dbeef01c0043275f9a0e7'
- global_messages: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals_cm4 functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_c13ca997a68f2ca6c666916ba13db7d7'
- functional_group: 'BOARD_InitPeripherals_cm4'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
    - dma_channels:
      - 0:
        - apiMode: 'trans'
        - dma_channel:
          - channel_prefix_id: 'CH0'
          - DMA_source: 'kDmaRequestFlexcomm0Rx'
          - init_channel_priority: 'false'
          - dma_priority: 'kDMA_ChannelPriority0'
          - enable_custom_name: 'false'
        - peripheral_request: 'false'
        - init_trigger_config: 'false'
        - trigger_config:
          - type: 'kDMA_NoTrigger'
          - burst: 'kDMA_SingleTransfer'
          - wrap: 'kDMA_NoWrap'
        - trans_config:
          - init_callback: 'false'
          - callback_function: ''
          - callback_user_data: ''
        - tcd_config:
          - 0:
            - tcdID: 'CH0_TCD0'
            - linkToNextTCD: 'noDescriptor'
            - transferCfg:
              - reload: 'false'
              - clrTrig: 'true'
              - intA: 'false'
              - intB: 'false'
              - width: 'kDMA_Transfer8BitWidth'
              - srcInc: 'kDMA_AddressInterleave1xWidth'
              - dstInc: 'kDMA_AddressInterleave1xWidth'
              - transBytes: '1024'
            - srcAddr:
              - addrType: 'startAddr'
              - addr_expr: '&StartAddress'
              - addr_def: 'uint8_t StartAddress[1024]'
            - dstAddr:
              - addrType: 'startAddr'
              - addr_expr: '&EndAddress'
              - addr_def: 'uint8_t EndAddress[1024]'
        - allocateTCD: 'noncache'
        - initTCD: 'CH0_TCD0'
    - dma_interrupt_trans:
      - IRQn: 'DMA0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

  /* Channel CH0 global variables */
dma_handle_t DMA0_CH0_Handle;
/* CH0_TCD0 source address extern definition */
extern uint8_t StartAddress[1024];
/* CH0_TCD0 destination address extern definition */
extern uint8_t EndAddress[1024];
AT_NONCACHEABLE_SECTION_ALIGN( dma_descriptor_t DMA0_CH0_TCDs_config[1], FSL_FEATURE_DMA_LINK_DESCRIPTOR_ALIGN_SIZE )
 = {
  {
    .xfercfg = DMA_CHANNEL_XFER(false, true, false, false, kDMA_Transfer8BitWidth, kDMA_AddressInterleave1xWidth, kDMA_AddressInterleave1xWidth, 1024U),
    .srcEndAddr = (void *)DMA_DESCRIPTOR_END_ADDRESS(&StartAddress, (uint32_t)kDMA_AddressInterleave1xWidth, 1024U, (uint32_t)kDMA_Transfer8BitWidth),
    .dstEndAddr = (void *)DMA_DESCRIPTOR_END_ADDRESS(&EndAddress, (uint32_t)kDMA_AddressInterleave1xWidth, 1024U, (uint32_t)kDMA_Transfer8BitWidth),
    .linkToNextDesc = NULL
  }
};

void DMA0_init(void) {

  /* Channel CH0 initialization */
  /* Enable the DMA 0channel in the DMA */
  DMA_EnableChannel(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* Create the DMA DMA0_CH0_Handlehandle */
  DMA_CreateHandle(&DMA0_CH0_Handle, DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* DMA0 transfer submit */
  DMA_SubmitChannelDescriptor(&DMA0_CH0_Handle, &DMA0_CH0_TCD0_config);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals_cm4(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);

  /* Initialize components */
  DMA0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals_cm4();
}
